### ISSUE TITLE
Pokémon X Y not working

### ISSUE THREAD

**Issue by SilentSand7** [Thulinma/ndsplus#13]
NDS Adapter Plus freezes when I put Pokémon Y in it until I remove it. If this is just me let me know, if not I look forward to the next patch/update.

**Comment by Thulinma** [comment]
A new firmware update will be needed - I'm sure EMS is already aware and working on it.

**Comment by Antar1011** [comment]
I went ahead and emailed EMS to ask for an estimate. Here was the reply:

"Thank you for your email. We are sorry that we don't have an time estimation for this yet. We will post any news on our message board, and our website as soon as possible."

Just posting so that presumably others won't harass EMS like I did.

**Comment by Thulinma** [comment]
Thanks for the update on this, saves the rest of us some time. :-)

**Comment by Antar1011** [comment]
Just received the following message from EMS:

I am sorry that [3DS] Pokemon X & Y is not compatible with #0907 NDS Adaptor Plus. It is impossible to be fixed by upgrading the firmware.

#0907 NDS Adaptor Plus are designed to read the game save from EEPROM of the cart. As [3DS] Pokemon X & Y doesn't has EEPROM, it is not supported by NDS Adaptor Plus. Please see the attached picture.
![3ds](https://f.cloud.github.com/assets/1105113/1357832/54faea44-37a6-11e3-9b82-74d8ad4357d8.jpg)

So the NDS Adapter will _never_ support X&Y. I guess that means that those of us looking for backup solutions are back to square one.

**Comment by Thulinma** [comment]
Makes sense. I guess it only stores data on the 3DS and/or SD card then.

**Comment by SilentSand7** [comment]
Weird I've been using it in different systems with different SD cards. Nintendo really went all out to remove cheating on these games. This really blows and I hope Nintendo doesn't do this for every game from this point on or a solution/new device is created.
